# frozen_string_literal: true

source 'https://rubygems.org'

gem 'sinatra', '~> 4.1.0'
gem 'sentry-ruby', '~> 5.22.0'
gem 'puma', '~> 6.5.0'
gem 'rackup', '~> 2.2.1'

group :test do
  gem 'rspec', '~> 3.13.0'
  gem 'rack-test', '~> 2.1.0'
  gem 'simplecov', '~> 0.22.0'
end
